const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const e = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n = value => Number(value || 0).toLocaleString('zh-CN');
const date = value => new Date(value).toLocaleString('zh-CN',{hour12:false});
const key = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const state = {view:'inventory',parts:[],movements:[],boms:[],q:'',category:'',status:'',sort:'id',direction:-1,page:1,selected:new Set(),bom:null};
const titles = {inventory:'元件库存',bom:'BOM 查缺',history:'出入库流水',settings:'数据与备份'};
let toastTimer;
function toast(message,error=false) { const t=$('#toast');t.textContent=message;t.className=error?'error':'';t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',5000); }
async function api(url,options={}) {
  const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers},body:options.body ? JSON.stringify(options.body) : undefined});
  const data=await response.json(); if (!response.ok) throw new Error(data.error || '操作失败'); return data;
}
async function run(fn,button) {
  if (button) button.disabled=true;
  try { return await fn(); } catch(error) {toast(error.message,true);} finally {if(button)button.disabled=false;}
}
function modal(title,html,wide=false) {const d=$('#modal');d.classList.toggle('wide',wide);$('#modal-content').innerHTML=`<div class="modal-title"><h2>${e(title)}</h2><button type="button" aria-label="关闭" data-close>×</button></div>${html}`;if(!d.open)d.showModal();$('[data-close]').onclick=()=>d.close();$$('[data-cancel]').forEach(b=>b.onclick=()=>d.close());}
const footer=(label='保存')=>`<div class="form-footer"><button type="button" data-cancel>取消</button><button type="submit" class="primary">${label}</button></div>`;
const empty=(title,message,action='')=>`<div class="empty"><span class="empty-icon">▦</span><h3>${title}</h3><p>${message}</p>${action}</div>`;
function stat(label,value,caption='') {return `<div class="stat"><span class="stat-label">${label}</span><strong>${value}</strong><small>${caption}</small></div>`;}
const badges={enough:['good','库存足够'],shortage:['warn','数量不足'],unmatched:['bad','待匹配'],excluded:['','不装 / 零用量']};
function statusBadge(status){const b=badges[status]||['',''];return `<span class="badge ${b[0]}">${b[1]}</span>`;}
async function refresh(){
  const [parts,movements,boms]=await Promise.all([api('/api/parts'),api('/api/movements'),api('/api/boms')]);
  Object.assign(state,{parts,movements,boms});
  if(state.bom)state.bom=await api(`/api/boms/${state.bom.id}`);
  $('#connection').textContent='服务已连接';$('#connection').style.color='';render();
}
function render(){ $('#page-title').textContent=titles[state.view];$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));({inventory:renderInventory,bom:renderBom,history:renderHistory,settings:renderSettings}[state.view])(); }
function filteredParts(){
  const q=state.q.trim().toUpperCase().replace(/\s/g,'');
  return state.parts.filter(p=>!q||Object.values(p).join(' ').toUpperCase().replace(/\s/g,'').includes(q)||q===`ICINV:${p.id}`)
    .filter(p=>!state.category||p.category===state.category)
    .filter(p=>!state.status||state.status==='low'&&p.quantity<=p.minStock||state.status==='zero'&&p.quantity===0||state.status==='reuse'&&p.condition==='拆机可用'||state.status==='pending'&&p.condition==='待检测')
    .sort((a,b)=>{const av=a[state.sort],bv=b[state.sort];return (typeof av==='number'?av-bv:String(av).localeCompare(String(bv),'zh-CN',{numeric:true}))*state.direction;});
}
function renderInventory(){
  const p=state.parts;
  $('#content').innerHTML=`<div class="stats">${stat('元件种类',n(p.length),'不同型号与封装')}${stat('库存总数量',n(p.reduce((s,v)=>s+v.quantity,0)),'全新、拆机及待检测')}${stat('库存预警',n(p.filter(v=>v.quantity<=v.minStock).length),'已到最低库存或无库存')}${stat('拆机可用',n(p.filter(v=>v.condition==='拆机可用').reduce((s,v)=>s+v.quantity,0)),'已确认可以再次使用')}</div>
  <section class="panel"><div class="panel-head"><h2>元件清单 <span class="badge">${p.length} 种</span></h2><div class="actions"><button data-action="import-stock">批量入库</button><button data-action="labels">打印标签 <span id="selected-count"></span></button><button class="primary" data-action="add">＋ 录入元件</button></div></div><div class="toolbar"><div class="search"><input id="inventory-search" aria-label="搜索元件" placeholder="搜索型号、立创编号、库位，或扫描二维码" value="${e(state.q)}"></div><select id="category-filter" aria-label="分类筛选"><option value="">所有分类</option>${[...new Set(p.map(v=>v.category))].sort().map(c=>`<option ${c===state.category?'selected':''}>${e(c)}</option>`).join('')}</select><select id="status-filter" aria-label="库存筛选"><option value="">所有库存</option><option value="low">库存预警</option><option value="zero">零库存</option><option value="reuse">拆机可用</option><option value="pending">待检测</option></select><button data-action="export-stock">导出</button></div><div id="inventory-table"></div></section>`;
  $('#status-filter').value=state.status;
  $('#inventory-search').oninput=event=>{state.q=event.target.value;state.page=1;inventoryTable();};
  $('#category-filter').onchange=event=>{state.category=event.target.value;state.page=1;inventoryTable();};
  $('#status-filter').onchange=event=>{state.status=event.target.value;state.page=1;inventoryTable();};
  inventoryTable();
}
function inventoryTable(){
  const parts=filteredParts(),pageSize=30,maxPage=Math.max(1,Math.ceil(parts.length/pageSize));state.page=Math.min(state.page,maxPage);
  const page=parts.slice((state.page-1)*pageSize,state.page*pageSize);
  const th=(label,field)=>`<th><button data-sort="${field}">${label} ${state.sort===field?(state.direction===1?'↑':'↓'):'↕'}</button></th>`;
  $('#inventory-table').innerHTML=parts.length?`<div class="table-wrap"><table><thead><tr><th><input type="checkbox" id="select-all" aria-label="选择本页元件" ${page.every(p=>state.selected.has(p.id))?'checked':''}></th>${th('内部编号','code')}${th('型号 / 参数','mpn')}${th('封装','footprint')}${th('分类','category')}${th('库位','location')}${th('库存','quantity')}<th>状态</th><th>操作</th></tr></thead><tbody>${page.map(p=>`<tr><td><input type="checkbox" data-select="${p.id}" aria-label="选择 ${e(p.code)}" ${state.selected.has(p.id)?'checked':''}></td><td><button class="link-button code" data-action="detail" data-id="${p.id}">${e(p.code)}</button><span class="sub">${e(p.lcsc||'—')}</span></td><td><span class="part-name">${e(p.mpn)}</span><span class="sub">${e([p.value,p.manufacturer].filter(Boolean).join(' · ')||'—')}</span></td><td>${e(p.footprint||'—')}</td><td><span class="badge">${e(p.category)}</span></td><td>${e(p.location||'未分配')}</td><td><span class="qty ${p.quantity<=p.minStock?'low':''}">${n(p.quantity)}</span><span class="sub">最低 ${n(p.minStock)}</span></td><td><span class="badge ${p.condition==='拆机可用'?'good':p.condition==='待检测'?'warn':''}">${e(p.condition)}</span></td><td><div class="row-actions"><button class="link-button" data-action="in" data-id="${p.id}">入库</button><button class="link-button" data-action="out" data-id="${p.id}">出库</button><button class="link-button" data-action="edit" data-id="${p.id}">编辑</button></div></td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>共 ${n(parts.length)} 种 · 已选 ${state.selected.size} 种</span><div class="pagination"><button data-action="prev" ${state.page===1?'disabled':''}>上一页</button><span>${state.page} / ${maxPage}</span><button data-action="next" ${state.page===maxPage?'disabled':''}>下一页</button></div></div>`:
    empty(state.parts.length?'没有找到元件':'开始整理你的元件库',state.parts.length?'试试型号、立创编号或存放位置。':'先录入一包已购元件，或批量导入采购表格。',state.parts.length?'':'<button class="primary" data-action="add">录入第一种元件</button>');
  $('#selected-count').textContent=state.selected.size?`(${state.selected.size})`:'';
  $$('[data-sort]').forEach(b=>b.onclick=()=>{if(state.sort===b.dataset.sort)state.direction*=-1;else{state.sort=b.dataset.sort;state.direction=1;}inventoryTable();});
  $$('[data-select]').forEach(c=>c.onchange=()=>{const id=Number(c.dataset.select);c.checked?state.selected.add(id):state.selected.delete(id);inventoryTable();});
  if($('#select-all'))$('#select-all').onchange=event=>{page.forEach(p=>event.target.checked?state.selected.add(p.id):state.selected.delete(p.id));inventoryTable();};
}
function partForm(id){
  const p=state.parts.find(p=>p.id===Number(id))||{};
  const input=(label,k,placeholder='',type='text',extra='')=>`<label>${label}<input name="${k}" type="${type}" value="${e(p[k]??'')}" placeholder="${placeholder}" ${extra}></label>`;
  modal(p.id?'编辑元件':'录入元件',`<form id="part-form"><div class="form-grid">${input('型号 *','mpn','例如 TPS55288RPMR','text','required')}${input('内部编号','code','留空自动生成 IC-000001')}${input('立创编号','lcsc','例如 C2687986')}${input('封装','footprint','例如 VQFN-26')}${input('参数 / 规格','value','例如 10µF / 50V / X7R')}${input('制造商','manufacturer','例如 Texas Instruments')}<label>分类<input name="category" list="categories" value="${e(p.category||'IC')}"><datalist id="categories">${['IC','电阻','电容','电感','MOS管','二极管','连接器','模块','其他',...state.parts.map(p=>p.category)].filter((v,i,a)=>a.indexOf(v)===i).map(c=>`<option>${e(c)}</option>`).join('')}</datalist></label>${input('存放位置','location','例如 A柜 / 02盒 / 03格')}<label>来源类型<select name="condition">${['全新','拆机可用','待检测'].map(c=>`<option ${p.condition===c?'selected':''}>${c}</option>`).join('')}</select></label>${p.id?`<label>当前库存<input value="${n(p.quantity)}" disabled></label>`:input('初始入库数量','quantity','0','number','min="0" step="1"')}${input('最低库存预警','minStock','0','number','min="0" step="1"')}${input('采购单价（元 / 个）','price','0','number','min="0" step="0.0001"')}<label class="full">备注<textarea name="notes" placeholder="购买来源、耐压、批次、拆机检测情况等">${e(p.notes||'')}</textarea></label></div><p id="duplicate-hint" class="note"></p>${footer(p.id?'保存修改':'录入并入库')}</form>`);
  const form=$('#part-form');
  if(!p.id){const mpn=form.elements.mpn;mpn.oninput=()=>{const duplicates=state.parts.filter(v=>v.mpn.toUpperCase()===mpn.value.trim().toUpperCase());$('#duplicate-hint').textContent=duplicates.length?`已有同型号：${duplicates.map(v=>`${v.code} · ${v.footprint} · 库存 ${v.quantity}`).join('；')}。如是同一种元件，可取消后直接入库。`:'';};}
  form.onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));for(const k of ['minStock','price','quantity'])if(data[k]==='')data[k]=0;if(!p.id)data.key=key();run(async()=>{await api(p.id?`/api/parts/${p.id}`:'/api/parts',{method:p.id?'PATCH':'POST',body:data});$('#modal').close();await refresh();toast(p.id?'元件已更新':'元件已入库');},$('button[type=submit]',form));};
}
function movementForm(id,type){
  const p=state.parts.find(v=>v.id===Number(id));
  modal(`${type} · ${p.code}`,`<form id="movement-form"><div class="callout"><strong>${e(p.mpn)}</strong> · ${e(p.footprint)}<br>当前库存 ${n(p.quantity)} 个 · 库位 ${e(p.location||'未分配')}</div><div class="form-grid" style="margin-top:18px"><label>${type==='盘点'?'实际盘点数量':'本次'+type+'数量'}<input name="quantity" type="number" min="${type==='盘点'?0:1}" step="1" required autofocus></label><label>关联项目 / 采购来源<input name="reference" placeholder="例如 P4 Energy Core / 立创采购"></label><label class="full">备注<textarea name="notes" placeholder="用途、订单号、回收检测结果等"></textarea></label></div>${footer('确认'+type)}</form>`);
  const form=$('#movement-form'),operationKey=key();form.onsubmit=event=>{event.preventDefault();run(async()=>{await api(`/api/parts/${p.id}/movements`,{method:'POST',body:{...Object.fromEntries(new FormData(form)),type,key:operationKey}});$('#modal').close();await refresh();toast(`${type}成功`);},$('button[type=submit]',form));};
}
function detail(id){
  const p=state.parts.find(v=>v.id===Number(id));if(!p)return;
  modal(p.mpn,`<div class="callout"><strong>${e(p.code)}</strong> · 当前库存 <strong>${n(p.quantity)}</strong> 个</div>${[['立创编号',p.lcsc],['参数 / 封装',[p.value,p.footprint].filter(Boolean).join(' · ')],['位置',p.location],['分类 / 来源',`${p.category} · ${p.condition}`],['制造商',p.manufacturer],['单价',`¥${n(p.price)}`],['备注',p.notes]].map(([k,v])=>`<div class="detail-row"><span>${k}</span><span>${e(v||'—')}</span></div>`).join('')}<div class="actions" style="margin:18px 0"><button data-action="in" data-id="${p.id}">入库</button><button data-action="out" data-id="${p.id}">出库</button><button data-action="count" data-id="${p.id}">盘点</button><button data-action="label-one" data-id="${p.id}">打印二维码</button><button class="danger" data-action="archive" data-id="${p.id}" ${p.quantity?'disabled':''}>归档</button></div><p class="note">扫码枪可搜索：ICINV:${p.id}。零库存元件可以归档，出入库历史会保留。</p><h3>最近流水</h3><div class="table-wrap"><table class="mini-history"><thead><tr><th>时间</th><th>操作</th><th>变动</th><th>结余</th></tr></thead><tbody>${state.movements.filter(m=>m.partId===p.id).slice(0,8).map(m=>`<tr><td>${date(m.createdAt)}</td><td>${e(m.type)}</td><td>${m.delta>0?'+':''}${m.delta}</td><td>${m.balance}</td></tr>`).join('')||'<tr><td colspan="4">暂无流水</td></tr>'}</tbody></table></div>`);
}
async function fileInput(file){return {name:file.name,data:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);})};}
async function importTable(kind,input){
  const parsed=await api('/api/import/parse',{method:'POST',body:input});
  const labels={mpn:'型号',lcsc:'立创编号',code:'内部编号',footprint:'封装',quantity:'数量 *',designators:'位号',value:'参数',manufacturer:'制造商',category:'分类',location:'库位',minStock:'最低库存',price:'单价',notes:'备注',condition:'来源类型',dnp:'不装 / 加入BOM'};
  const keys=kind==='bom'?['mpn','lcsc','code','footprint','quantity','designators','value','dnp']:['mpn','lcsc','code','footprint','quantity','value','manufacturer','category','location','minStock','price','condition','notes'];
  modal(kind==='bom'?'导入 BOM · 确认列映射':'批量入库 · 确认列映射',`<form id="import-form"><div class="callout ${kind==='stock'?'warning':''}">${kind==='stock'?'数量列代表本次新增入库数量，会累加到已有库存；同编号型号冲突时整批不入库。':'导入只用于查缺，确认领料时才扣减库存。型号或编号至少映射一项；不会自动选择近似替代料。'}</div><div class="form-grid" style="margin-top:16px">${kind==='bom'?`<label>项目 / BOM 名称<input name="bom-name" value="${e((input.name||'我的 BOM').replace(/\.[^.]+$/,''))}" required></label><label>制作板数<input name="boards" type="number" min="1" step="1" value="1" required></label>`:''}<label>工作表<select id="sheet-choice">${parsed.sheets.map(s=>`<option ${s===parsed.sheet?'selected':''}>${e(s)}</option>`).join('')}</select></label><span class="note">已识别 ${parsed.rows.length} 行 · 表头位于第 ${parsed.headerRow+1} 行</span></div><div class="mapping">${keys.map(k=>`<label>${labels[k]}<select name="map-${k}"><option value="">不导入</option>${parsed.columns.map(c=>`<option value="${e(c)}" ${parsed.mapping[k]===c?'selected':''}>${e(c)}</option>`).join('')}</select></label>`).join('')}</div><p class="note">原始表格预览（前 5 行）</p><div class="preview-table"><table><thead><tr>${parsed.columns.map(c=>`<th>${e(c)}</th>`).join('')}</tr></thead><tbody>${parsed.rows.slice(0,5).map(r=>`<tr>${parsed.columns.map(c=>`<td>${e(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${footer(kind==='bom'?'导入并对比库存':'确认批量入库')}</form>`,true);
  $('#sheet-choice').onchange=event=>run(()=>importTable(kind,{...input,sheet:event.target.value}));
  const form=$('#import-form'),operationKey=key();form.onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form)),mapping=Object.fromEntries(keys.map(k=>[k,data[`map-${k}`]]));run(async()=>{
    const result=await api(kind==='bom'?'/api/boms':'/api/import/stock',{method:'POST',body:{rows:parsed.rows,mapping,key:operationKey,name:data['bom-name'],boards:data.boards}});
    $('#modal').close();if(kind==='bom'){state.bom=result;state.view='bom';}await refresh();toast(kind==='bom'?'BOM 已导入，查缺结果已生成':`新建 ${result.created} 种，入库更新 ${result.updated} 种`);
  },$('button[type=submit]',form));};
}
function uploadDialog(kind){
  modal(kind==='bom'?'导入嘉立创 BOM':'批量入库',`<div class="upload-box"><span class="empty-icon">⇧</span><h3>${kind==='bom'?'选择嘉立创 EDA 导出的 BOM':'选择采购表格或库存表格'}</h3><p>支持 CSV、TSV、TXT、XLSX、XLS<br>自动识别中英文表头，可在下一步调整列映射。</p><button class="primary" id="choose-file">选择文件</button><input type="file" id="table-file" accept=".csv,.tsv,.txt,.xlsx,.xls"></div><p class="note">也可以直接从 Excel 复制表格（包含表头）：</p><textarea id="paste-table" style="width:100%" placeholder="型号\t封装\t数量\nTPS55288RPMR\tVQFN-26\t2"></textarea><div class="form-footer"><button data-cancel>取消</button><button id="paste-import">解析粘贴内容</button></div>`);
  $('#choose-file').onclick=()=>$('#table-file').click();$('#table-file').onchange=event=>{const file=event.target.files[0];if(file){if(file.size>10*1024*1024)return toast('单个文件最大 10 MiB',true);run(async()=>importTable(kind,await fileInput(file)));}};
  $('#paste-import').onclick=event=>run(()=>importTable(kind,{text:$('#paste-table').value,name:'粘贴 BOM'}),event.currentTarget);
}
function renderBom(){
  const b=state.bom;
  if(!b){$('#content').innerHTML=`<div class="grid2"><section class="panel settings-card"><h2>用现有库存，检查下一块板</h2><p>导入嘉立创 EDA 的 BOM，填写板数，核对元件匹配。查缺结果会显示可领数量和需要采购的缺口。</p><div class="upload-box"><span class="empty-icon">≡</span><h3>从 BOM 开始</h3><p>CSV / Excel · 支持标准版与专业版列映射</p><button class="primary" data-action="import-bom">导入 BOM</button></div><p class="note">先按立创编号匹配，再核对型号与封装；近似参数不会自动视为替代料。</p></section><section class="panel"><div class="panel-head"><h2>已保存 BOM</h2><span class="badge">${state.boms.length} 份</span></div>${state.boms.length?`<div class="bom-list">${state.boms.map(b=>`<div class="bom-item"><div><button class="link-button" data-action="open-bom" data-id="${b.id}">${e(b.name)}</button><span class="sub">${date(b.createdAt)} · ${b.boards} 块板</span></div><span class="badge ${b.status==='issued'?'good':''}">${b.status==='issued'?'已领料':'待领料'}</span></div>`).join('')}</div>`:empty('还没有 BOM','导入后会保存在服务器，可随时继续查缺。')}</section></div>`;return;}
  const issued=b.status==='issued',lines=issued?b.issueResult.lines:b.lines,summary=issued?b.issueResult.summary:b.summary;
  $('#content').innerHTML=`<div class="actions" style="margin-bottom:20px"><button data-action="back-boms">全部 BOM</button><span class="note">${e(b.name)} · ${date(b.createdAt)}</span><button data-action="import-bom">导入新 BOM</button></div><div class="stats">${stat('本次需求',n(summary.required),'按板数和备料比例计算')}${stat('库存足够',n(summary.enough)+' 项',`${summary.lines} 项有效用料`)}${stat('需采购',n(summary.missing)+' 个',`${summary.shortage} 项数量不足 · ${summary.unmatched} 项待匹配`)}${stat(issued?'领料前最多可做':'按库存最多可做',n(summary.maxBoards)+' 块','合并同元件用量，含备料比例')}</div>
  ${issued?`<div class="callout" style="margin-bottom:20px">已于 ${date(b.issuedAt)} ${b.issueResult.partial?'按现有数量领料':'完成整单领料'}。以下保存领料时的结果；库存已扣减，此 BOM 不会再次领料。${b.issueResult.partial?'未领足的数量见采购缺口清单。':''}</div>`:''}
  <section class="panel"><div class="panel-head"><h2>${e(b.name)}</h2><div class="actions"><button data-action="export-bom">导出对比表</button><button data-action="export-shortage">导出采购缺口</button><button class="primary" data-action="issue-bom" ${issued?'disabled':''}>${issued?'已领料':'确认领料'}</button></div></div><div class="bom-controls"><label>制作板数<input id="bom-boards" type="number" min="1" step="1" value="${b.boards}" ${issued?'disabled':''}></label><label>备料比例<input id="bom-spare" type="number" min="0" max="100" step="0.1" value="${b.sparePercent}" ${issued?'disabled':''}> %</label>${issued?'':'<button data-action="recompare">重新计算</button>'}<span class="note">同一元件多行累计占用；每行向上取整。</span></div><div class="table-wrap"><table><thead><tr><th>位号 / BOM 元件</th><th>封装</th><th>匹配库存</th><th>单板</th><th>总需求</th><th>可领</th><th>缺少</th><th>结果</th><th>操作</th></tr></thead><tbody>${lines.map((l,i)=>`<tr><td><span class="part-name">${e(l.mpn||l.lcsc||l.code)}</span><span class="sub">${e(l.designators||'—')} · ${e(l.lcsc)}</span></td><td>${e(l.footprint||'—')}</td><td>${l.part?`<span class="code">${e(l.part.code)}</span><span class="sub">${e(l.part.mpn)} · ${e(l.part.location||'未分配')}</span>`:'<span class="sub">尚未选择库存元件</span>'}<span class="sub">${e(l.reason)}</span></td><td>${n(l.quantity)}</td><td>${n(l.required)}</td><td><span class="qty">${n(l.allocated)}</span></td><td><span class="qty ${l.shortage?'low':''}">${n(l.shortage)}</span></td><td>${statusBadge(l.status)}</td><td>${issued?'—':`<button class="link-button" data-action="match" data-id="${i}">${l.part?'改匹配':'选元件'}</button><br><button class="link-button" data-action="exclude" data-id="${i}">${l.excluded?'恢复用料':'不装'}</button>`}</td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>匹配结果只用于库存查缺；手动选择替代料前请核对参数与封装。</span></div></section>`;
}
function matchDialog(index){
  const line=state.bom.lines[index];
  modal('选择库存元件',`<div class="callout">BOM：${e(line.mpn||line.lcsc)} · ${e(line.footprint||'未指定封装')}<br>手动选择表示你已确认型号、封装和参数可用。</div><input class="match-search" id="match-search" aria-label="搜索候选元件" placeholder="搜索型号、编号、参数或库位" style="margin-top:18px"><div id="match-results" style="max-height:360px;overflow:auto"></div><div class="form-footer"><button id="clear-match">取消此行匹配</button><button data-cancel>关闭</button></div>`);
  const show=()=>{const q=$('#match-search').value.toUpperCase();const parts=state.parts.filter(p=>p.condition!=='待检测'&&Object.values(p).join(' ').toUpperCase().includes(q));parts.sort((a,b)=>Number(line.candidates.includes(b.id))-Number(line.candidates.includes(a.id)));$('#match-results').innerHTML=parts.slice(0,80).map(p=>`<div class="match-option"><div><span class="part-name">${e(p.mpn)} <span class="badge">${e(p.footprint)}</span></span><span class="sub">${e(p.code)} · ${e(p.lcsc)} · ${e(p.value)} · ${e(p.location)} · ${e(p.condition)}</span></div><div><span class="qty">${n(p.quantity)}</span> <button data-match-id="${p.id}">选择</button></div></div>`).join('')||'<p class="note">没有找到可用元件。待检测元件需要先编辑为可用状态。</p>';$$('[data-match-id]').forEach(button=>button.onclick=()=>choose(Number(button.dataset.matchId),button));};
  const choose=(id,button)=>run(async()=>{state.bom=await api(`/api/boms/${state.bom.id}`,{method:'PATCH',body:{lineIndex:index,partId:id}});$('#modal').close();renderBom();},button);
  $('#match-search').oninput=show;$('#clear-match').onclick=event=>choose(null,event.currentTarget);show();
}
function issueDialog(){
  const b=state.bom,s=b.summary,missing=s.shortage+s.unmatched>0;
  modal('确认 BOM 领料',`<form id="issue-form"><div class="callout ${missing?'warning':''}"><strong>${e(b.name)} · ${b.boards} 块板</strong><br>需求 ${n(s.required)} 个，现有可领 ${n(s.required-s.missing)} 个，缺口 ${n(s.missing)} 个。${missing?'<br>尚有缺料或未匹配行，可以先采购，或只领取现有数量。':''}</div><p class="note">确认后立即扣减库存并记录流水，此 BOM 只能领料一次。需要剩余用料时，请按缺口清单另建 BOM。</p>${missing?'<label class="check-label"><input name="partial" type="checkbox" required> 只领取已匹配且现有的数量，保留缺口记录</label>':''}${footer('确认扣减库存')}</form>`);
  const form=$('#issue-form'),operationKey=key();form.onsubmit=event=>{event.preventDefault();run(async()=>{await api(`/api/boms/${b.id}/issue`,{method:'POST',body:{key:operationKey,partial:Boolean(form.elements.partial?.checked)}});$('#modal').close();await refresh();toast('领料完成，库存和流水已更新');},$('button[type=submit]',form));};
}
function renderHistory(){
  $('#content').innerHTML=`<section class="panel"><div class="panel-head"><h2>出入库记录</h2><div class="actions"><span class="badge">${n(state.movements.length)} 笔</span><button data-action="export-history">导出流水</button></div></div><div class="toolbar"><div class="search"><input id="history-search" aria-label="搜索流水" placeholder="搜索型号、编号、关联项目或备注"></div><select id="history-type" aria-label="流水类型"><option value="">全部操作</option>${['入库','出库','盘点','BOM领料'].map(v=>`<option>${v}</option>`).join('')}</select></div><div id="history-table"></div></section>`;
  const show=()=>{const q=$('#history-search').value.toUpperCase(),type=$('#history-type').value;const rows=state.movements.filter(m=>(!q||Object.values(m).join(' ').toUpperCase().includes(q))&&(!type||m.type===type));$('#history-table').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>时间</th><th>元件</th><th>操作</th><th>变动前</th><th>变动</th><th>结余</th><th>关联 / 备注</th></tr></thead><tbody>${rows.slice(0,300).map(m=>`<tr><td>${date(m.createdAt)}</td><td><span class="part-name">${e(m.mpn)}</span><span class="sub code">${e(m.code)}</span></td><td><span class="badge ${m.delta>0?'good':''}">${e(m.type)}</span></td><td>${n(m.previous)}</td><td style="color:${m.delta>0?'#237d62':'#bc6b28'}">${m.delta>0?'+':''}${n(m.delta)}</td><td><strong>${n(m.balance)}</strong></td><td>${e(m.reference||'—')}<span class="sub">${e(m.notes)}</span></td></tr>`).join('')}</tbody></table></div><div class="table-footer">共 ${n(rows.length)} 笔，显示最近 300 笔；导出包含全部记录。</div>`:empty('暂无流水','入库、出库、盘点和 BOM 领料都会自动留痕。');};$('#history-search').oninput=show;$('#history-type').onchange=show;show();
}
function renderSettings(){
  $('#content').innerHTML=`<div class="grid2"><section class="panel settings-card"><h2>数据备份</h2><p>完整备份包含元件、库存、流水、BOM 和编号序列。更换服务器时可以用它恢复。</p><button class="primary" data-action="backup">下载完整备份</button><hr style="border:0;border-top:1px solid var(--line);margin:24px 0"><h3>恢复备份</h3><p>恢复会替换当前数据；服务器会先保存一份恢复前备份。</p><button data-action="restore">选择备份恢复</button><input type="file" id="restore-file" accept=".json" hidden></section><section class="panel settings-card"><h2>二维码与家庭访问</h2><p>填写家庭服务器访问地址后，标签二维码可直接打开元件详情。留空则生成稳定元件 ID，适合扫码枪输入搜索框。</p><label class="form-label">服务器访问地址<input id="label-base" placeholder="例如 http://192.168.1.20:3210" value="${e(localStorage.getItem('label-base')||'')}"></label><button id="save-label-base" style="margin-top:14px">保存标签地址</button><p class="note">只在本浏览器保存标签地址。库存数据保存在服务器。</p><h3>当前服务</h3><p id="server-info">正在读取…</p></section></div><section class="panel settings-card"><h2>日常使用顺序</h2><p>① 新买元件先录入或入库，并记录库位。<br>② 设计前用型号、立创号或参数搜索，优先复用现有元件。<br>③ 从嘉立创 EDA 导出 BOM，在「BOM 查缺」导入并核对匹配。<br>④ 设置板数、导出缺口采购；焊接领料时再确认扣减库存。<br>⑤ 拆机元件检测后以「拆机可用」入库，未检测的标记「待检测」。</p></section>`;
  $('#save-label-base').onclick=()=>{const value=$('#label-base').value.trim().replace(/\/$/,'');if(value&&!/^https?:\/\/[^\s]+$/i.test(value))return toast('请填写 http:// 或 https:// 开头的访问地址',true);localStorage.setItem('label-base',value);toast('标签地址已保存');};
  run(async()=>{const info=await api('/api/info');if($('#server-info'))$('#server-info').textContent=`版本 ${info.version}；数据：${info.dataDir}；本机网络地址：${info.addresses.join('、')||'无局域网地址'}`;});
  $('#restore-file').onchange=event=>{const file=event.target.files[0];if(!file)return;run(async()=>{const snapshot=JSON.parse(await file.text());modal('恢复完整备份',`<form id="restore-form"><div class="callout warning">备份时间：${e(snapshot.exportedAt?date(snapshot.exportedAt):'未知')}<br>元件 ${snapshot.parts?.length??'?'} 种，流水 ${snapshot.movements?.length??'?'} 笔。<br>恢复会替换服务器当前库存、流水和 BOM。</div><label class="form-label" style="margin-top:16px">输入「恢复备份」确认<input name="confirm" required autocomplete="off"></label>${footer('恢复备份')}</form>`);const form=$('#restore-form');form.onsubmit=event=>{event.preventDefault();run(async()=>{await api('/api/restore',{method:'POST',body:{snapshot,confirm:form.elements.confirm.value}});$('#modal').close();state.bom=null;state.selected.clear();await refresh();toast('备份已恢复，恢复前数据已自动保留');},$('button[type=submit]',form));};});};
}
function download(url){const a=document.createElement('a');a.href=url;a.download='';a.click();}
function printLabels(ids){if(!ids.length)return toast('请先勾选需要打印标签的元件',true);if(ids.length>200)return toast('一次最多打印 200 张标签',true);window.open(`/api/labels?ids=${ids.join(',')}&base=${encodeURIComponent(localStorage.getItem('label-base')||'')}`,'_blank');}
document.addEventListener('click',event=>{
  const button=event.target.closest('[data-action]');if(!button)return;
  const action=button.dataset.action,id=button.dataset.id;
  const actions={add:()=>partForm(),edit:()=>partForm(id),detail:()=>detail(id),in:()=>movementForm(id,'入库'),out:()=>movementForm(id,'出库'),count:()=>movementForm(id,'盘点'),
    'import-stock':()=>uploadDialog('stock'),'import-bom':()=>uploadDialog('bom'),'export-stock':()=>download('/api/parts/export'),labels:()=>printLabels([...state.selected]),'label-one':()=>printLabels([id]),prev:()=>{state.page--;inventoryTable();},next:()=>{state.page++;inventoryTable();},
    'back-boms':()=>{state.bom=null;renderBom();},'open-bom':async()=>{state.bom=await api(`/api/boms/${id}`);renderBom();},'export-bom':()=>download(`/api/boms/${state.bom.id}/export`),'export-shortage':()=>download(`/api/boms/${state.bom.id}/export?shortage=1`),'issue-bom':async()=>{state.bom=await api(`/api/boms/${state.bom.id}`,{method:'PATCH',body:{boards:$('#bom-boards').value,sparePercent:$('#bom-spare').value}});renderBom();issueDialog();},match:()=>matchDialog(Number(id)),
    recompare:async()=>{state.bom=await api(`/api/boms/${state.bom.id}`,{method:'PATCH',body:{boards:$('#bom-boards').value,sparePercent:$('#bom-spare').value}});renderBom();toast('已按最新库存重新计算');},exclude:async()=>{state.bom=await api(`/api/boms/${state.bom.id}`,{method:'PATCH',body:{lineIndex:Number(id),excluded:!state.bom.lines[id].excluded}});renderBom();},
    'export-history':()=>download('/api/movements/export'),backup:()=>download('/api/backup'),restore:()=>$('#restore-file').click(),archive:()=>{const p=state.parts.find(p=>p.id===Number(id));modal('归档元件',`<p class="note">归档 ${e(p.code)} · ${e(p.mpn)}，隐藏元件并保留流水。</p><div class="form-footer"><button data-cancel>取消</button><button class="danger" id="confirm-archive">确认归档</button></div>`);$('#confirm-archive').onclick=event=>run(async()=>{await api(`/api/parts/${id}`,{method:'DELETE'});$('#modal').close();state.selected.delete(Number(id));await refresh();toast('已归档');},event.currentTarget);}};
  if(actions[action])run(actions[action],button);
});
$$('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;render();});
$('#refresh').onclick=event=>run(refresh,event.currentTarget);
$('#clock').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short'});
$('#content').innerHTML='<div class="busy">正在读取库存…</div>';
run(async()=>{await refresh();const part=new URLSearchParams(location.search).get('part');if(part)detail(part);}).then(()=>{if(!state.parts.length&&$('#connection').textContent==='连接中'){$('#connection').textContent='连接失败';$('#connection').style.color='#ffb9ae';$('#content').innerHTML=empty('暂时无法连接服务器','请确认服务已启动，然后点击刷新。');}});
